### ISSUE TITLE
adding a GUID to each user agent record

### ISSUE THREAD

**Issue by amandato** [opawg/user-agents#109]
We are looking at synchronizing our user agent list with this one and would find it very useful if there was a consistent unique identifier (GUID) associated to each record. Such an identifier would be also be useful for the situation where the application name changes also.

GUID: In this case would be a 128-bit integer number used to identify the user agent with a well-defined sequence of 32 hexadecimal digits grouped as 8-4-4-4-12

Example of the proposed addition to the first 2 records found in the json...

` "guid": "f93bfaff-f0ac-4e44-bb52-2ca0aafcbd01",`

`[
    {
       "guid": "f93bfaff-f0ac-4e44-bb52-2ca0aafcbd01",
        "user_agents": [
            "^Acast.+[Aa]ndroid"
        ],
        "app": "Acast",
        "device": "phone",
        "os": "android"
    },
    {
       "guid": "476757ae-28b4-47ed-94dd-753cf4832cdb",
        "user_agents": [
            "^Acast.+iOS"
        ],
        "app": "Acast",
        "device": "phone",
        "os": "ios"
    },
    ...]` (also [attached)](url)

This would allow a developer to pull this json file, check the guid with what was saved to identify when a record should be updated vs inserted as new. The GUID could be used to match the title of the app and the regular expression used and if the "user_agent" or the "app" changed, then the application would know what record to update.

The result would require that all new user agents added include a unique guid. Thoughts?

Thanks!

--Angelo

![user_agent_example_guids](https://user-images.githubusercontent.com/3031332/152592241-ede91397-6acf-41d9-bc6e-d12caa2ba17f.png)

**Comment by jamescridland** [comment]
I'm up for doing this if it makes life simpler for developers. I can see there being benefits. Are we specifying a completely random [UUIDv4](https://www.uuidtools.com/v4) here, following RFC 4122?

One UUID for distinct combinations of app/device/os, yes? So, if Acast (as above) releases a version of their app for KaiOS, this would be a new UUID?

Further, if Pocket Casts ever changes their useragent to highlight OS, so we can split them into iOS and Android separately, that would mean one new UUID being given (and the other record edited)?

(Strictly - should this be "guid" or "uuid" in this JSON?)

**Comment by amandato** [comment]
> One UUID for distinct combinations of app/device/os, yes? So, if Acast (as above) releases a version of their app for KaiOS, this would be a new UUID?

Yes and yes. If it did not have a new uuid, then we would simply update the current acast with the additional user_agent strings/regex.

> Further, if Pocket Casts ever changes their user agent to highlight OS, so we can split them into iOS and Android separately, that would mean one new UUID being given (and the other record edited)?

This is where things get messy, and is how our database of user agents from years back evolved. Back when Stitcher launched iOS and Android apps and right away had iOS and Android mentioned in their user agents, we did exactly this, but since we found that if an application used the same user agent then one day added the OS it we simply reported the OS separately but continued to report the app without identifying the user agent. Up until this past year we made the decision that if the application had less than 2% marketspace that breaking out the OS was not relevant enough. We've come full circle with this thinking and now, if we can separate by OS we will. It's just more data for the podcaster to sift through.

My suggestion is, if an application that works on multi-OS's up to a certain point reports as the app only, then after a certain point in time reports the OS, it should be treated as a separate "new" record with a new uuid, this allows for reporting shift / transition gradually as users update their apps on their devices. I think users will understand that in 2021 an app was just the app, and in 2022+ the app for iOS and the App for Android report as 2 different apps in reporting.

If the app changes their name and user agent, but it's still the same app (e.g. iPodder -> iPodder Lemon -> Juice all versions for Windows desktop), the "os" and "device" designation did not change in this case, then the "app" would just change to the latest name of the application, the "user_agent" would have all of the variations, and the "developer_notes" would note the past app names.


**Blubrry's Database**
Our database to detect user agents and report on them is structed very similar except OS is reported separately:

- clients table
- client regex table  - 1:n to the clients table
- client class table - n:1 to clients table (this is the same as your device + bot, basically we have class=bot or class=tablet, class=phone, etc..)
- platform table - equivalent to your os
- platform regex table - 1:n to the platform table

We report the platforms / os's separately today. We are looking at phasing this out and replacing with an os table that is n:1 to the clients table. Assuming we add the uuid's to this json, then we will simply pull this json file once a month, save the uuid to our clients table and know what records are new and which need updated, we would use the latest "app" and values in "user_agents" for syncing, and new records would associate their "os" and "device" values to our client class and new os tables.

Two situations in our OS table that you do not have, we have "Multi Platform" as 1 option for those applications that are on both iOS/Android and/or "Windows/Mac" but do not identify which OS they are coming from, as well as "Proprietary". We also report "ChromeOS", "Blackberry", "Windows Phone", "WebOS", and a handful of others that are what I would refer to as "legacy" today and if we did them now we just classify them into "proprietary" or "other".

**Thought**: It would be ideal that every record always have a "os" and "device" value set and if either of those change, it would imply that there should be a new record with a new uuid.

This reminds me about iPodder Lemon/Juice, we have user agents going back to 2005 that we can provide, but I would suggest putting them in a separate user-agents.json file, maybe call it legacy-user-agents.json.

"uuid" would be more appropriate for JSON.

**Comment by jamescridland** [comment]
This is great. The original view from @amarksteadman was that we only put data we're sure of into this. So, if there's no OS given (like Pocket Casts), we don't guess one. Your "Multiplatform" is the equivalent of no OS entry; your "proprietary" should be, in my view, the actual name of the OS. If it only runs on Harmony, then that's the OS we report. Your end could ignore OSs that you don't recognise.

For your client class table - it's impossible to spot whether Android is a phone or tablet, which means that no Android devices (ought to) have a device type associated with them. In my view, Android devices are overwhelmingly phone, but that's a decision you can make on ingestion - some Android devices are actually also running ChromeOS.

Circling back to my original question - "Are we specifying a completely random UUIDv4 here, following RFC 4122?" If it's a completely random UUIDv4, should I populate this data with UUIDs today? I'm hoping it won't be a breaking change for anyone; it's an extra JSON data field that should be otherwise ignored.

(The RSS useragents have a concept of a 'slug', which is more human-readable, which can be used as a query string for the audio.)

**Comment by daveajones** [comment]
Glad to do this and promote it Angelo.  I like James's idea of generating them all and adding to the list.  Then I can just go get the Podcast Index's UUID from this list and start using it right away.

**Comment by jamescridland** [comment]
Thanks, Dave. I don't think you need to "use it" in any way - it's a random UUID for ingestion for analytics, so no need for you to change anything. Unless you had a dastardly idea I'd not considered!

**Comment by amandato** [comment]
I think Dave can use it right away in the context of using it as the key to know when a user agent changes or is added. :)

i like UUIDv4 myself, but it does not have to be a uuid, it could be an incremented number as long as it is unique we're good.

Is there a full list of the OS's? I can make a quick script to get from the json if not.

As for tablet vs phone, are in the same boat we can only separate them out today via iPads, and we're looking at calling them ipads rather than tablets.

**Comment by jamescridland** [comment]
I'm happy to do this; but @amandato no longer works at Blubrry, so just managing my time here. If anyone would like a UUID adding to each, I'd be happy to.
