### ISSUE TITLE
feature: $schema keyword

### ISSUE THREAD

**Issue by foolioo** [opawg/user-agents#110]
Firstly, **thank you for the fine work!**

> [The `$schema` keyword is used to declare which dialect of JSON Schema the schema was written for. The value of the `$schema` keyword is also the identifier for a schema that can be used to verify that the schema is valid according to the dialect `$schema` identifies.](https://json-schema.org/understanding-json-schema/reference/schema.html#id4)

What do you think of adding the `$schema` key to [`user-agenst.json`](https://github.com/opawg/user-agents/blob/master/src/user-agents.json). It's value could reference locally, or better yet - point to the [json schema store URL](https://www.schemastore.org/json/), such as https://json.schemastore.org/github-workflow-template-properties.json (for more information, see [schema repositories](https://json-schema.org/implementations.html#schema-repositories))?

[VSCode honors the $schema keyworkd](https://code.visualstudio.com/Docs/languages/json#_json-schemas-and-settings) and many [schema validators](https://json-schema.org/implementations.html#validators) could be used.

I could open a pull-request with the change, but I am reaching for the maintainers opinion to know whether the schema should be published to schema store and use a global URL or use a local reference

**Comment by jamescridland** [comment]
Thanks for this!

Could you let me know the problem that we run without having a `$schema` keyword, and the benefit of adding it?

What are the benefits of publishing a schema to schema store, rather than using a local reference?

**Comment by foolioo** [comment]
> What are the benefits of publishing a schema to schema store, rather than using a local reference?

1. if one can copies the file, there is no need to copy the other one.
2. the schema can be utilized by other projects easily, and maybe become the de-facto standard

> Could you let me know the problem that we run without having a $schema keyword, and the benefit of adding it?

there is no problem, it just makes editing more easily (one knows there is a schema and some IDE's honors it). plus, a validator tools, use this to validate the file schema match its specifications.

**Comment by jamescridland** [comment]
Closing for now; you're welcome to make a pull request if it's valuable.
