### ISSUE TITLE
Feature request: Sample strings

### ISSUE THREAD

**Issue by majkiee** [opawg/user-agents#12]
Would be great to have samples of the user agents for each of the regex sections. That would simplify writing tests for the implementation on different platforms.
It would also be helpful in the future when writing updates for missing / new versions since you can compare the newly reported user-agent with the already existing one and adjust the rule to cover both or add an additional.

**Comment by jamescridland** [comment]
There are now a bunch of these in the JSON file, which is excellent work; and we have a way to add more.

Please do help by adding more that you're aware of. :)
