### ISSUE TITLE
Feature Request: Version Numbers in Github

### ISSUE THREAD

**Issue by dan** [opawg/user-agents#28]
Friends,

Would it be possible to create releases/version numbers for when the list is updated? That would make it much easier to coordinate updates of gems, such as https://github.com/dan/podcast_agent_parser/ which relies on your fantastic list.

Thanks!

**Comment by jamescridland** [comment]
Hi, Dan. Well, it's been six months, and nobody's come back to you! Oops.

If there's a way to do this with Github, that would be great - I don't know, otherwise, what the best approach would be. Hints very gratefully received.
