### ISSUE TITLE
Soprify bot regex may filter valid requests

### ISSUE THREAD

**Issue by vparpoil** [opawg/user-agents#36]
Hello, 
It appears that the [spotify bot regex ](https://github.com/opawg/user-agents/blob/bd1d0d1fd76309ffbdd5e57b0636c9ee7754ce23/src/user-agents.json#L1345) : `^Spotify/\\d+` is not restrictive enough and may match other Soptify user agents that are not related to bots (see [here](https://developers.whatismybrowser.com/useragents/explore/software_name/spotify/1) a wide list).  
Can we update the Regex to exactly match the `Spotify/1.0` user agent, i.e : `^Spotify/\\d+\.\\d+$` ?

**Comment by jamescridland** [comment]
Thanks for the patch; and done.
