### ISSUE TITLE
Wrong format for user_agents key

### ISSUE THREAD

**Issue by majkiee** [opawg/user-agents#42]
This record has the wrong key, it has `user-agents` instead of `user_agents`

https://github.com/opawg/user-agents/blob/c5f3ad39646bff25a33b0dbc4579867aa7fb20b7/src/user-agents.json#L1604

**Comment by pierrocknroll** [comment]
Sorry, my fault

**Comment by jamescridland** [comment]
I'd be grateful for a pull request to fix it, please. :)

**Comment by pierrocknroll** [comment]
@majkiee you can close
