### ISSUE TITLE
Quantifier at the beginning of the regex

### ISSUE THREAD

**Issue by lisfox1** [opawg/user-agents#43]
I think this is invalid, quantifier should not be at the beginning of the regex.
https://github.com/opawg/user-agents/blob/dcd5d787959ad9a0878504263a2f9b15aa473abd/src/user-agents.json#L636

**Comment by jamescridland** [comment]
I'd be grateful for a pull request to fix it.

**Comment by lisfox1** [comment]
> I'd be grateful for a pull request to fix it.

https://github.com/opawg/user-agents/pull/44
