### ISSUE TITLE
One non-valid Regex

### ISSUE THREAD

**Issue by jamescridland** [opawg/user-agents#71]
From my error logs, there's one non-valid regex pattern in the current JSON. I'm not clever enough to quite work out where. I'll continue that work, but just flagging this as an error.

**Comment by SlimBeji** [comment]
I think there are more than one non-valid Regex.

Here an example:
```iPhone.*AppleWebKit.*Safari/(?!.*(AdsBot/)```

It is clearly missing a closing parenthesis at the end.

This one too, same issue
```"Macintosh.*AppleWebKit(?!.*(Chrome\/)).*Safari/(?!.*(AdsBot/)"```

**Comment by jamescridland** [comment]
I think you're probably right, and my apologies.

I shall [implement a check](https://stackoverflow.com/questions/4440626/how-can-i-validate-regex) on this to ensure it works correctly.

**Comment by SlimBeji** [comment]
I made a pull request with tests using pytest

**Comment by jamescridland** [comment]
You're super kind. Thank you.
